services:
  # Main web service
  - type: web
    name: attendance-system
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/attendance.db
      - key: SESSION_SECRET
        generateValue: true
      - key: DEFAULT_ADMIN_PASSWORD
        value: admin123
      - key: HTTPS
        value: true
    
  # Background worker for database management
  - type: worker
    name: attendance-db-manager
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node render-db-worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/attendance.db
      - key: SESSION_SECRET
        sync: attendance-system
      - key: WORKER_INTERVAL
        value: 120

  # Cron job for scheduled tasks
  - type: cron
    name: attendance-maintenance
    env: node
    plan: starter
    buildCommand: npm install
    schedule: "0 2 * * *"  # Daily at 2 AM UTC
    startCommand: node render-maintenance.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/attendance.db